### PR TITLE
Fix string-adjacency bugs

### LINKED ISSUE #7: Unexpected parsing results
I ran into some unexpected parsing results.

When including `=` (equals sign) in the input string:

```hs
ShellWords.parse "foo=123 bar" == Right ["foo=123", "bar"]
-- Fail: Instead it parses as Right ["foo"]

ShellWords.parse "foo bar=123 cow" == Right ["foo", "bar=123", "cow"]
-- Fail: Instead it parses as ["foo","bar"]
```

When escaping any reserved character by putting it within quotes:

```hs
ShellWords.parse "foo bar'();='bar cow" == Right ["foo", "bar();=bar", "cow"]
-- Fail: Instead it parses as Right ["foo","bar'"]
```

When parsing adjacent quoted strings:

```hs
ShellWords.parse "foo 'ba'\"r\" cow" == Right ["foo","bar","cow"]
-- Fail: Instead it parses as Right ["foo","ba"]
```

First, it wasn't immediately clear to me what was going wrong, since instead of returning an error the library simply returned a truncated version of the input. Perhaps we shouldn't return a `Right` when the string failed to parse correctly / completely.

As for the first case with the equals sign: I don't think an equal sign should have any special handling. The only case where the shell does so is at the start of the line (see [the specification](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#tag_19_10_02)); which doesn't seem desirable for the primary use case this library describes in its README.

(And if we want to add an environment parsing option like the Python library has, it should be fairly trivial to split the list in a separate function).

There is also a number of characters that probably *should* be marked as reserved and be required to be escaped. [Here](https://unix.stackexchange.com/a/270979) is a fairly good overview.

For reference, how I tested how the shell parses arguments by checking what various programming languages get passed to their `argv`:

```
python -c 'import sys; print(repr(sys.argv))' ...args
perl -e 'use Data::Dump qw(dump); print dump(@ARGV);' ...args
node -e 'console.log(process.argv)' ...args
php -r 'var_dump($argv);' ...args
ruby -e 'print ARGV' ...args
```

### PR DESCRIPTION
**Pull request by pbrisbin**
Fixes #7.

### CODE REVIEW

File: src/ShellWords.hs [hunk 1]
```diff
@@ -28,50 +26,34 @@ parse :: String -> Either String [String]
 parse = runParser parser
 
 runParser :: Parser a -> String -> Either String a
-runParser p = first errorBundlePretty . Megaparsec.parse p "<input>"
+runParser p = first errorBundlePretty . Megaparsec.parse (p <* eof) "<input>"
```
Comment (pbrisbin) [inline src/ShellWords.hs:29]: Technically, this is a behavior change that could warrant major -- but I'm going to consider it a bug-fix as it was always the intention it should behave this way.

File: src/ShellWords.hs [hunk 2]
```diff
@@ -28,50 +26,34 @@ parse :: String -> Either String [String]
...
 
 shellword :: Parser String
-shellword =
-  choice
-    [ quoted <?> "quoted string"
-    , shelloption <?> "shell option"
-    , value <?> "bare value"
-    ]
-    <?> "shell word"
+shellword = fmap concat $ some $ bare <|> quoted
```
Comment (pbrisbin) [inline src/ShellWords.hs:39]: Very neat that handling string-adjacency like this actually simplified everything.

File: test/ShellWordsSpec.hs [hunk 3]
```diff
@@ -39,27 +39,13 @@ testCases =
   , ("var --bar=baz\\ bat", ["var", "--bar=baz bat"])
   , ("var --bar baz\\ bat", ["var", "--bar", "baz bat"])
   , -- N.B. sh preserves escapes in quoted values, python-shellwords does not.
-    -- we behave like sh in this regard. See omitted cases below too.
+    -- we behave like sh in this regard.
     ("var --bar 'baz\\ bat'", ["var", "--bar", "baz\\ bat"])
   , ("var  --bar \"baz\\ bat\"", ["var", "--bar", "baz\\ bat"])
+  , ("var \"--bar=\\\\'baz\\\\'\"", ["var", "--bar=\\'baz\\'"])
+  , ("var --bar='\\\\'", ["var", "--bar=\\"])
```
Comment (pbrisbin) [inline test/ShellWordsSpec.hs:46]: It might've just been my inability to correctly put the double-`\\` escapes in the test input that prevented me having these cases enabled before :shrug:
